version: '2.1'
services:
  plasma_root:
    image: plasma-evm/root
    networks:
      plasma:
        ipv4_address: ${ROOTCHAIN_IP}
    build:
      context: ./containers/docker/rootchain
      dockerfile: Dockerfile
    healthcheck:
      test: echo 'checking health'
      interval: 60s
      timeout: 30s
      retries: 5
    ports:
    - "0.0.0.0:8545:8545"
    - "0.0.0.0:8546:8546"
    command: sh run.rootchain.sh

  plasma_bootnode:
    image: plasma-evm/bootnode
    networks:
      plasma:
        ipv4_address: ${BOOTNODE_IP}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      plasma_root:
        condition: service_started
    ports:
      - "0.0.0.0:30301:30301"
    command: sh docker.bootnode.sh

  plasma_child_operator:
    image: plasma-evm/child
    networks:
      plasma:
        ipv4_address: ${OPERATOR_IP}
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: echo 'checking health'
      interval: 60s
      timeout: 30s
      retries: 5
    depends_on:
      plasma_root:
        condition: service_started
      plasma_bootnode:
        condition: service_started
    ports:
    - "0.0.0.0:8547:8547"
    - "0.0.0.0:8548:8548"
    command: sh docker.operator.pls.sh

  plasma_child_user:
    image: plasma-evm/child
    networks:
        plasma:
          ipv4_address: ${USER_IP}
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
        plasma_root:
          condition: service_healthy
        plasma_child_operator:
          condition: service_healthy
    ports:
      - "0.0.0.0:8549:8549"
      - "0.0.0.0:8550:8550"
    command: sh docker.user.pls.sh

networks:
  plasma:
    driver: bridge
    ipam:
      config:
      - subnet: 172.30.0.0/24
        gateway: 172.30.0.1

