version: '2.3'
services:
  root:
    image: plasma-evm/root
    cpus: 0.5
    networks:
      plasma:
        ipv4_address: ${ROOTCHAIN_IP}
    build:
      context: ./containers/docker/rootchain
      dockerfile: Dockerfile
    healthcheck:
      test: echo 'checking health'
      interval: 60s
      timeout: 30s
      retries: 5
    ports:
      - "0.0.0.0:8545:8545"
      - "0.0.0.0:8546:8546"
    command: sh run.rootchain.sh

  fast_root:
    image: plasma-evm/root
    cpus: 1
    networks:
      - plasma
    build:
      context: ./containers/docker/rootchain
      dockerfile: Dockerfile
    command: sh run.fastroot.sh

  bootnode:
    image: plasma-evm/bootnode
    networks:
      plasma:
        ipv4_address: ${BOOTNODE_IP}
    build:
      context: .
      dockerfile: Dockerfile.plasma
      target: bootnode
    ports:
      - "0.0.0.0:30301:30301"
    command: sh docker.bootnode.sh

  operator:
    image: plasma-evm/child
    networks:
      plasma:
        ipv4_address: ${OPERATOR_IP}
    build:
      context: .
      dockerfile: Dockerfile.plasma
      target: geth
    healthcheck:
      test: echo 'checking health'
      interval: 60s
      timeout: 30s
      retries: 5
    depends_on:
      root:
        condition: service_started
    ports:
      - "0.0.0.0:8547:8547"
      - "0.0.0.0:8548:8548"
    command: sh docker.operator.pls.sh

networks:
  plasma:
    driver: bridge
    ipam:
      config:
      - subnet: 172.30.0.0/24
        gateway: 172.30.0.1